#!/usr/bin/env python3

import numpy as np
import time
import json
import os
import shutil

from mainProgram import mainP

folder=os.getcwd()


for strain in np.arange(0,0.0031,0.0005):
  pd={}
  pd["strain"]=strain

  pd['intdir']= os.path.join(folder, f"strain_{strain:.4f}") #contains output of singleP
  pd['rootdir']= folder #contains all scripts
  pd['outdir'] = os.path.join(folder, f"results_{strain:.4f}") #HF results output
  
  print(pd['intdir'])
  os.chdir(pd['rootdir'])
  
  #load external input (mainly to get 'intdir' and 'rootdir')
  with open("HF_input.json") as f:
    pd_input = json.load(f)
  pd = {**pd,**pd_input}
  
  #load json file generated by singleP
  with open(os.path.join(pd['intdir'],'int_pd.json')) as f:
    pd_int = json.load(f)
  pd = {**pd,**pd_int}
  
  pd['filling'] = 2
  
  # =============================================================================
  # Code Execution
  # =============================================================================
  
  start_time = time.time() #start timer
  
  
  N1=pd['N1'];N2=pd['N2']
  
  
  for boost in [0,4]:
    for seed in range(10):
      pd['seed']=seed
      pd['boost1'] = boost
      


      if boost==0:
        pd["in_choice"]="random"
      if boost>0:
        if seed%2==0:
          pd["in_choice"]="random"
        if seed%2==1:
          pd["in_choice"]="BM"
      
      dir_name = pd['outdir'] + f"/b{boost:d}_s{seed:d}"
      if os.path.isdir(dir_name):
        shutil.rmtree(dir_name)
      os.makedirs(dir_name)
      os.chdir(dir_name)
      
      E,out,P_new, HFeigs,fill_index,evecs=mainP(pd)
      
      with open('output.json', 'w') as f:
        json.dump(out, f, indent=2)
      
      with open('HF_pd.json', 'w') as f:
        json.dump(pd, f, indent=2)
      
      np.save('P.npy', P_new)
      np.save('HFeigs.npy', HFeigs)
      
      print("\n--- example2_mainProgram.py done: %.2f seconds ---" % (time.time() - start_time))
