#!/usr/bin/env python3
# FOR TESTING PURPOSE

import numpy as np
import time
import json
import os
import shutil

from mainProgram import mainP

pd={}

pd['intdir']= os.path.join(os.getcwd(), "bandstructure") #contains output of test_singleParticle.py
pd['outdir'] = os.path.join(os.getcwd(), "results") #HF results output

#load external input
with open("HF_input.json") as f:
  pd_input = json.load(f)
pd = {**pd,**pd_input}

#load json file generated by test_singleParticle.py
with open(os.path.join(pd['intdir'],'int_pd.json')) as f:
  pd_int = json.load(f)
pd = {**pd,**pd_int}

# =============================================================================
# Code Execution
# =============================================================================

start_time = time.time() #start timer

boost1 = pd["boost1"];boost2=pd["boost2"];seed=pd["seed"]
dir_name = pd['outdir'] + f"/b{boost1:d}_{boost2:d}_s{seed:d}"
if os.path.isdir(dir_name):
  shutil.rmtree(dir_name)
os.makedirs(dir_name)
os.chdir(dir_name)

E,out,P_new, HFeigs,fill_index,evecs=mainP(pd)

with open('output.json', 'w') as f:
  json.dump(out, f, indent=2)

with open('HF_pd.json', 'w') as f:
  json.dump(pd, f, indent=2)

np.save('P.npy', P_new)
np.save('HFeigs.npy', HFeigs)

print("\n--- test_mainProgram done: %.2f seconds ---" % (time.time() - start_time))
